"""Add system events and processing latency

Revision ID: 3b9cca423480
Revises: 3eaf9ef40edd
Create Date: 2026-06-25 18:27:59.399120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9cca423480'
down_revision: Union[str, Sequence[str], None] = '3eaf9ef40edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_correlation_id'), 'system_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_id'), 'system_events', ['id'], unique=False)
    op.create_index(op.f('ix_system_events_timestamp'), 'system_events', ['timestamp'], unique=False)
    op.create_table('threat_intelligence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('threat_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('malicious_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intelligence_id'), 'threat_intelligence', ['id'], unique=False)
    op.add_column('prediction_histories', sa.Column('processing_latency', sa.Float(), nullable=True))
    op.add_column('threats', sa.Column('mitre_technique', sa.String(), nullable=True))
    op.add_column('threats', sa.Column('recommended_action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threats', 'recommended_action')
    op.drop_column('threats', 'mitre_technique')
    op.drop_column('prediction_histories', 'processing_latency')
    op.drop_index(op.f('ix_threat_intelligence_id'), table_name='threat_intelligence')
    op.drop_table('threat_intelligence')
    op.drop_index(op.f('ix_system_events_timestamp'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_correlation_id'), table_name='system_events')
    op.drop_table('system_events')
    # ### end Alembic commands ###
