"""Add preprocessing tables

Revision ID: 55411fac9507
Revises: 54e620ee9852
Create Date: 2026-06-25 15:20:04.197394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55411fac9507'
down_revision: Union[str, Sequence[str], None] = '54e620ee9852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('numeric_features', sa.JSON(), nullable=True),
    sa.Column('categorical_features', sa.JSON(), nullable=True),
    sa.Column('class_distribution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id')
    )
    op.create_index(op.f('ix_dataset_profiles_id'), 'dataset_profiles', ['id'], unique=False)
    op.create_table('preprocessing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preprocessing_jobs_id'), 'preprocessing_jobs', ['id'], unique=False)
    op.create_table('processed_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_dataset_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('train_features_path', sa.String(), nullable=False),
    sa.Column('train_labels_path', sa.String(), nullable=False),
    sa.Column('test_features_path', sa.String(), nullable=False),
    sa.Column('test_labels_path', sa.String(), nullable=False),
    sa.Column('train_samples', sa.Integer(), nullable=False),
    sa.Column('test_samples', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['preprocessing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_processed_datasets_id'), 'processed_datasets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_datasets_id'), table_name='processed_datasets')
    op.drop_table('processed_datasets')
    op.drop_index(op.f('ix_preprocessing_jobs_id'), table_name='preprocessing_jobs')
    op.drop_table('preprocessing_jobs')
    op.drop_index(op.f('ix_dataset_profiles_id'), table_name='dataset_profiles')
    op.drop_table('dataset_profiles')
    # ### end Alembic commands ###
